const sampleTemplates = [
    // Easy Words (20)
    { text: "Hello", textVi: "Xin chào", level: "easy", type: "word", category: "Greetings", order: 1 },
    { text: "Goodbye", textVi: "Tạm biệt", level: "easy", type: "word", category: "Greetings", order: 2 },
    { text: "Thank you", textVi: "Cảm ơn", level: "easy", type: "word", category: "Courtesy", order: 3 },
    { text: "Please", textVi: "Làm ơn", level: "easy", type: "word", category: "Courtesy", order: 4 },
    { text: "Sorry", textVi: "Xin lỗi", level: "easy", type: "word", category: "Courtesy", order: 5 },
    { text: "Yes", textVi: "Có", level: "easy", type: "word", category: "Basic", order: 6 },
    { text: "No", textVi: "Không", level: "easy", type: "word", category: "Basic", order: 7 },
    { text: "Water", textVi: "Nước", level: "easy", type: "word", category: "Food & Drink", order: 8 },
    { text: "Food", textVi: "Thức ăn", level: "easy", type: "word", category: "Food & Drink", order: 9 },
    { text: "Help", textVi: "Giúp đỡ", level: "easy", type: "word", category: "Basic", order: 10 },
    { text: "Friend", textVi: "Bạn bè", level: "easy", type: "word", category: "Relationships", order: 11 },
    { text: "Family", textVi: "Gia đình", level: "easy", type: "word", category: "Relationships", order: 12 },
    { text: "Happy", textVi: "Vui vẻ", level: "easy", type: "word", category: "Emotions", order: 13 },
    { text: "Beautiful", textVi: "Đẹp", level: "easy", type: "word", category: "Adjectives", order: 14 },
    { text: "Good", textVi: "Tốt", level: "easy", type: "word", category: "Adjectives", order: 15 },
    { text: "Bad", textVi: "Xấu", level: "easy", type: "word", category: "Adjectives", order: 16 },
    { text: "Big", textVi: "To", level: "easy", type: "word", category: "Adjectives", order: 17 },
    { text: "Small", textVi: "Nhỏ", level: "easy", type: "word", category: "Adjectives", order: 18 },
    { text: "New", textVi: "Mới", level: "easy", type: "word", category: "Adjectives", order: 19 },
    { text: "Old", textVi: "Cũ", level: "easy", type: "word", category: "Adjectives", order: 20 },

    // Easy Sentences (20)
    { text: "How are you?", textVi: "Bạn khỏe không?", level: "easy", type: "sentence", category: "Greetings", order: 21 },
    { text: "I am fine, thank you.", textVi: "Tôi khỏe, cảm ơn.", level: "easy", type: "sentence", category: "Greetings", order: 22 },
    { text: "What is your name?", textVi: "Tên bạn là gì?", level: "easy", type: "sentence", category: "Introduction", order: 23 },
    { text: "My name is John.", textVi: "Tên tôi là John.", level: "easy", type: "sentence", category: "Introduction", order: 24 },
    { text: "Nice to meet you.", textVi: "Rất vui được gặp bạn.", level: "easy", type: "sentence", category: "Greetings", order: 25 },
    { text: "Where are you from?", textVi: "Bạn đến từ đâu?", level: "easy", type: "sentence", category: "Introduction", order: 26 },
    { text: "I am from Vietnam.", textVi: "Tôi đến từ Việt Nam.", level: "easy", type: "sentence", category: "Introduction", order: 27 },
    { text: "Can you help me?", textVi: "Bạn có thể giúp tôi không?", level: "easy", type: "sentence", category: "Requests", order: 28 },
    { text: "I need water.", textVi: "Tôi cần nước.", level: "easy", type: "sentence", category: "Basic Needs", order: 29 },
    { text: "This is my friend.", textVi: "Đây là bạn của tôi.", level: "easy", type: "sentence", category: "Introduction", order: 30 },
    { text: "I love my family.", textVi: "Tôi yêu gia đình mình.", level: "easy", type: "sentence", category: "Family", order: 31 },
    { text: "Today is a good day.", textVi: "Hôm nay là một ngày tốt lành.", level: "easy", type: "sentence", category: "Daily Life", order: 32 },
    { text: "I am happy.", textVi: "Tôi hạnh phúc.", level: "easy", type: "sentence", category: "Emotions", order: 33 },
    { text: "The weather is nice.", textVi: "Thời tiết đẹp.", level: "easy", type: "sentence", category: "Weather", order: 34 },
    { text: "I like this book.", textVi: "Tôi thích quyển sách này.", level: "easy", type: "sentence", category: "Preferences", order: 35 },
    { text: "See you tomorrow.", textVi: "Hẹn gặp lại ngày mai.", level: "easy", type: "sentence", category: "Farewells", order: 36 },
    { text: "Have a nice day.", textVi: "Chúc bạn một ngày tốt lành.", level: "easy", type: "sentence", category: "Wishes", order: 37 },
    { text: "I understand.", textVi: "Tôi hiểu rồi.", level: "easy", type: "sentence", category: "Understanding", order: 38 },
    { text: "Please speak slowly.", textVi: "Làm ơn nói chậm lại.", level: "easy", type: "sentence", category: "Requests", order: 39 },
    { text: "Thank you very much.", textVi: "Cảm ơn bạn rất nhiều.", level: "easy", type: "sentence", category: "Gratitude", order: 40 },

    // Medium Words (10)
    { text: "Responsibility", textVi: "Trách nhiệm", level: "medium", type: "word", category: "Abstract", order: 41 },
    { text: "Achievement", textVi: "Thành tựu", level: "medium", type: "word", category: "Success", order: 42 },
    { text: "Environment", textVi: "Môi trường", level: "medium", type: "word", category: "Nature", order: 43 },
    { text: "Communication", textVi: "Giao tiếp", level: "medium", type: "word", category: "Skills", order: 44 },
    { text: "Opportunity", textVi: "Cơ hội", level: "medium", type: "word", category: "Business", order: 45 },
    { text: "Experience", textVi: "Kinh nghiệm", level: "medium", type: "word", category: "Work", order: 46 },
    { text: "Knowledge", textVi: "Kiến thức", level: "medium", type: "word", category: "Education", order: 47 },
    { text: "Relationship", textVi: "Mối quan hệ", level: "medium", type: "word", category: "Social", order: 48 },
    { text: "Development", textVi: "Phát triển", level: "medium", type: "word", category: "Progress", order: 49 },
    { text: "Technology", textVi: "Công nghệ", level: "medium", type: "word", category: "Modern", order: 50 },

    // Medium Sentences (20)
    { text: "I am learning English to improve my career.", textVi: "Tôi đang học tiếng Anh để cải thiện sự nghiệp.", level: "medium", type: "sentence", category: "Education", order: 51 },
    { text: "Technology has changed the way we communicate.", textVi: "Công nghệ đã thay đổi cách chúng ta giao tiếp.", level: "medium", type: "sentence", category: "Technology", order: 52 },
    { text: "We should protect the environment for future generations.", textVi: "Chúng ta nên bảo vệ môi trường cho thế hệ tương lai.", level: "medium", type: "sentence", category: "Environment", order: 53 },
    { text: "Reading books helps expand your knowledge.", textVi: "Đọc sách giúp mở rộng kiến thức của bạn.", level: "medium", type: "sentence", category: "Education", order: 54 },
    { text: "Good communication is essential in the workplace.", textVi: "Giao tiếp tốt là điều cần thiết tại nơi làm việc.", level: "medium", type: "sentence", category: "Work", order: 55 },
    { text: "I believe hard work leads to success.", textVi: "Tôi tin rằng làm việc chăm chỉ dẫn đến thành công.", level: "medium", type: "sentence", category: "Motivation", order: 56 },
    { text: "Exercise regularly to maintain good health.", textVi: "Tập thể dục thường xuyên để duy trì sức khỏe tốt.", level: "medium", type: "sentence", category: "Health", order: 57 },
    { text: "Time management is crucial for productivity.", textVi: "Quản lý thời gian rất quan trọng cho năng suất.", level: "medium", type: "sentence", category: "Skills", order: 58 },
    { text: "Traveling broadens your perspective on life.", textVi: "Du lịch mở rộng góc nhìn của bạn về cuộc sống.", level: "medium", type: "sentence", category: "Travel", order: 59 },
    { text: "Building strong relationships requires effort and trust.", textVi: "Xây dựng mối quan hệ bền chặt đòi hỏi nỗ lực và tin tưởng.", level: "medium", type: "sentence", category: "Relationships", order: 60 },
    { text: "Learning from mistakes helps us grow.", textVi: "Học hỏi từ sai lầm giúp chúng ta trưởng thành.", level: "medium", type: "sentence", category: "Life Lessons", order: 61 },
    { text: "The internet has made information more accessible.", textVi: "Internet đã làm cho thông tin dễ tiếp cận hơn.", level: "medium", type: "sentence", category: "Technology", order: 62 },
    { text: "Creativity is important in problem-solving.", textVi: "Sáng tạo quan trọng trong việc giải quyết vấn đề.", level: "medium", type: "sentence", category: "Skills", order: 63 },
    { text: "Setting goals helps you stay focused.", textVi: "Đặt mục tiêu giúp bạn duy trì sự tập trung.", level: "medium", type: "sentence", category: "Self-improvement", order: 64 },
    { text: "Social media influences modern society.", textVi: "Mạng xã hội ảnh hưởng đến xã hội hiện đại.", level: "medium", type: "sentence", category: "Society", order: 65 },
    { text: "Education opens doors to new opportunities.", textVi: "Giáo dục mở ra cánh cửa đến những cơ hội mới.", level: "medium", type: "sentence", category: "Education", order: 66 },
    { text: "We should respect cultural differences.", textVi: "Chúng ta nên tôn trọng sự khác biệt văn hóa.", level: "medium", type: "sentence", category: "Culture", order: 67 },
    { text: "Climate change is a global challenge.", textVi: "Biến đổi khí hậu là thách thức toàn cầu.", level: "medium", type: "sentence", category: "Environment", order: 68 },
    { text: "Teamwork makes difficult tasks easier.", textVi: "Làm việc nhóm làm cho nhiệm vụ khó khăn dễ dàng hơn.", level: "medium", type: "sentence", category: "Collaboration", order: 69 },
    { text: "Practice makes perfect in any skill.", textVi: "Luyện tập giúp hoàn thiện bất kỳ kỹ năng nào.", level: "medium", type: "sentence", category: "Learning", order: 70 },

    // Hard Words (10)
    { text: "Sustainability", textVi: "Tính bền vững", level: "hard", type: "word", category: "Environment", order: 71 },
    { text: "Entrepreneurship", textVi: "Tinh thần kinh doanh", level: "hard", type: "word", category: "Business", order: 72 },
    { text: "Innovation", textVi: "Sự đổi mới", level: "hard", type: "word", category: "Progress", order: 73 },
    { text: "Globalization", textVi: "Toàn cầu hóa", level: "hard", type: "word", category: "Economics", order: 74 },
    { text: "Consciousness", textVi: "Ý thức", level: "hard", type: "word", category: "Philosophy", order: 75 },
    { text: "Diversity", textVi: "Đa dạng", level: "hard", type: "word", category: "Society", order: 76 },
    { text: "Resilience", textVi: "Khả năng phục hồi", level: "hard", type: "word", category: "Psychology", order: 77 },
    { text: "Transparency", textVi: "Tính minh bạch", level: "hard", type: "word", category: "Ethics", order: 78 },
    { text: "Collaboration", textVi: "Sự cộng tác", level: "hard", type: "word", category: "Teamwork", order: 79 },
    { text: "Perspective", textVi: "Góc nhìn", level: "hard", type: "word", category: "Understanding", order: 80 },

    // Hard Sentences (20)
    { text: "The rapid advancement of artificial intelligence raises ethical questions about its impact on society.", textVi: "Sự tiến bộ nhanh chóng của trí tuệ nhân tạo đặt ra câu hỏi đạo đức về tác động của nó đối với xã hội.", level: "hard", type: "sentence", category: "Technology", order: 81 },
    { text: "Sustainable development requires balancing economic growth with environmental protection.", textVi: "Phát triển bền vững đòi hỏi cân bằng giữa tăng trưởng kinh tế và bảo vệ môi trường.", level: "hard", type: "sentence", category: "Environment", order: 82 },
    { text: "Globalization has interconnected economies, cultures, and societies across the world.", textVi: "Toàn cầu hóa đã kết nối các nền kinh tế, văn hóa và xã hội trên toàn thế giới.", level: "hard", type: "sentence", category: "Global Issues", order: 83 },
    { text: "Critical thinking is essential for analyzing complex problems and making informed decisions.", textVi: "Tư duy phản biện cần thiết để phân tích vấn đề phức tạp và đưa ra quyết định sáng suốt.", level: "hard", type: "sentence", category: "Skills", order: 84 },
    { text: "Innovation drives progress by introducing new ideas, methods, and technologies.", textVi: "Đổi mới thúc đẩy tiến bộ bằng cách giới thiệu ý tưởng, phương pháp và công nghệ mới.", level: "hard", type: "sentence", category: "Progress", order: 85 },
    { text: "Cultural diversity enriches society by bringing different perspectives and experiences together.", textVi: "Đa dạng văn hóa làm phong phú xã hội bằng cách kết hợp các quan điểm và kinh nghiệm khác nhau.", level: "hard", type: "sentence", category: "Culture", order: 86 },
    { text: "Resilience is the ability to adapt and recover from challenges and setbacks.", textVi: "Khả năng phục hồi là khả năng thích nghi và phục hồi từ thử thách và thất bại.", level: "hard", type: "sentence", category: "Psychology", order: 87 },
    { text: "Transparency in government fosters public trust and accountability.", textVi: "Tính minh bạch trong chính phủ nuôi dưỡng lòng tin của công chúng và trách nhiệm giải trình.", level: "hard", type: "sentence", category: "Politics", order: 88 },
    { text: "Effective collaboration requires clear communication, mutual respect, and shared goals.", textVi: "Hợp tác hiệu quả đòi hỏi giao tiếp rõ ràng, tôn trọng lẫn nhau và mục tiêu chung.", level: "hard", type: "sentence", category: "Teamwork", order: 89 },
    { text: "Understanding different perspectives helps us appreciate the complexity of human experience.", textVi: "Hiểu các góc nhìn khác nhau giúp chúng ta đánh giá cao sự phức tạp của trải nghiệm con người.", level: "hard", type: "sentence", category: "Philosophy", order: 90 },
    { text: "The intersection of science and ethics becomes increasingly important as technology advances.", textVi: "Sự giao thoa giữa khoa học và đạo đức ngày càng trở nên quan trọng khi công nghệ tiến bộ.", level: "hard", type: "sentence", category: "Science & Ethics", order: 91 },
    { text: "Economic inequality remains a significant challenge for modern societies worldwide.", textVi: "Bất bình đẳng kinh tế vẫn là thách thức đáng kể đối với các xã hội hiện đại trên toàn thế giới.", level: "hard", type: "sentence", category: "Economics", order: 92 },
    { text: "Mindfulness practices can enhance mental well-being and emotional regulation.", textVi: "Các thực hành chánh niệm có thể cải thiện sức khỏe tinh thần và điều chỉnh cảm xúc.", level: "hard", type: "sentence", category: "Mental Health", order: 93 },
    { text: "Interdisciplinary approaches often yield more comprehensive solutions to complex problems.", textVi: "Các cách tiếp cận liên ngành thường mang lại giải pháp toàn diện hơn cho các vấn đề phức tạp.", level: "hard", type: "sentence", category: "Research", order: 94 },
    { text: "The preservation of biodiversity is crucial for maintaining ecological balance.", textVi: "Bảo tồn đa dạng sinh học là rất quan trọng để duy trì cân bằng sinh thái.", level: "hard", type: "sentence", category: "Conservation", order: 95 },
    { text: "Ethical leadership involves making decisions that benefit stakeholders while upholding moral principles.", textVi: "Lãnh đạo có đạo đức bao gồm việc đưa ra quyết định có lợi cho các bên liên quan trong khi duy trì các nguyên tắc đạo đức.", level: "hard", type: "sentence", category: "Leadership", order: 96 },
    { text: "Digital literacy has become an essential skill in the modern information age.", textVi: "Kiến thức kỹ thuật số đã trở thành kỹ năng thiết yếu trong thời đại thông tin hiện đại.", level: "hard", type: "sentence", category: "Education", order: 97 },
    { text: "The concept of work-life balance reflects changing attitudes toward career and personal fulfillment.", textVi: "Khái niệm cân bằng công việc - cuộc sống phản ánh thái độ thay đổi đối với sự nghiệp và sự hoàn thành cá nhân.", level: "hard", type: "sentence", category: "Lifestyle", order: 98 },
    { text: "Geopolitical tensions continue to shape international relations and global stability.", textVi: "Căng thẳng địa chính trị tiếp tục định hình quan hệ quốc tế và ổn định toàn cầu.", level: "hard", type: "sentence", category: "International Relations", order: 99 },
    { text: "Empathy and compassion are fundamental to building inclusive and harmonious communities.", textVi: "Sự đồng cảm và lòng trắc ẩn là nền tảng để xây dựng cộng đồng hòa nhập và hòa hợp.", level: "hard", type: "sentence", category: "Social Values", order: 100 }
];

module.exports = { sampleTemplates };
